import { defineField, defineType } from 'sanity'

export const siteSettingsType = defineType({
	name: 'siteSettings',
	title: 'Pengaturan Website',
	type: 'document',
	groups: [
		{ name: 'umum', title: 'Umum' },
		{ name: 'profil', title: 'Profil' },
		{ name: 'kontak', title: 'Kontak' },
		{ name: 'sosmed', title: 'Sosial Media' },
		{ name: 'beranda', title: 'Beranda' },
		{ name: 'tampilan', title: 'Tampilan' },
		{ name: 'halaman', title: 'Halaman' },
	],
	fields: [
		defineField({
			name: 'siteName',
			title: 'Nama Yayasan',
			type: 'string',
			group: 'umum',
		}),
		defineField({
			name: 'shortName',
			title: 'Nama Singkat',
			type: 'string',
			group: 'umum',
		}),
		defineField({
			name: 'description',
			title: 'Deskripsi Website',
			type: 'text',
			rows: 3,
			group: 'umum',
		}),
		defineField({
			name: 'footerCopyright',
			title: 'Copyright Footer',
			type: 'string',
			initialValue: '\u00a9 2026 Yayasan Amal Shalih Insan Bantul',
			group: 'umum',
		}),
		defineField({
			name: 'visi',
			title: 'Visi',
			type: 'text',
			rows: 3,
			group: 'profil',
		}),
		defineField({
			name: 'misi',
			title: 'Misi',
			type: 'array',
			of: [{ type: 'string' }],
			group: 'profil',
		}),
		defineField({
			name: 'legal',
			title: 'Informasi Legal',
			type: 'object',
			group: 'profil',
			fields: [
				{ name: 'foundedDate', title: 'Tanggal Berdiri', type: 'string' },
				{ name: 'sk', title: 'SK Kemenkumham', type: 'string' },
				{ name: 'nib', title: 'NIB', type: 'string' },
				{ name: 'npwp', title: 'NPWP', type: 'string' },
				{ name: 'kbli', title: 'KBLI', type: 'string' },
			],
		}),
		defineField({
			name: 'aboutContent',
			title: 'Konten Halaman Tentang',
			type: 'blockContent',
			group: 'profil',
		}),
		defineField({
			name: 'address',
			title: 'Alamat',
			type: 'object',
			group: 'kontak',
			fields: [
				{ name: 'street', title: 'Jalan', type: 'string' },
				{ name: 'village', title: 'Desa/Kelurahan', type: 'string' },
				{ name: 'district', title: 'Kecamatan', type: 'string' },
				{ name: 'city', title: 'Kota/Kabupaten', type: 'string' },
				{ name: 'province', title: 'Provinsi', type: 'string' },
				{ name: 'postalCode', title: 'Kode Pos', type: 'string' },
			],
		}),
		defineField({
			name: 'phone',
			title: 'Telepon / WA',
			type: 'string',
			group: 'kontak',
		}),
		defineField({
			name: 'whatsapp',
			title: 'WhatsApp',
			type: 'string',
			group: 'kontak',
		}),
		defineField({
			name: 'email',
			title: 'Email',
			type: 'string',
			group: 'kontak',
		}),
		defineField({
			name: 'emails',
			title: 'Email Lainnya',
			type: 'object',
			group: 'kontak',
			fields: [
				{ name: 'info', title: 'Info', type: 'string' },
				{ name: 'donasi', title: 'Donasi', type: 'string' },
				{ name: 'admin', title: 'Admin', type: 'string' },
				{ name: 'humas', title: 'Humas', type: 'string' },
				{ name: 'gmail', title: 'Gmail', type: 'string' },
			],
		}),
		defineField({
			name: 'operatingHours',
			title: 'Jam Operasional',
			type: 'string',
			group: 'kontak',
		}),
		defineField({
			name: 'operatingHoursDetail',
			title: 'Detail Jam Operasional',
			type: 'object',
			group: 'kontak',
			fields: [
				{ name: 'weekdays', title: 'Senin–Jumat', type: 'string' },
				{ name: 'saturday', title: 'Sabtu', type: 'string' },
				{ name: 'sunday', title: 'Minggu', type: 'string' },
			],
		}),
		defineField({
			name: 'qrisImage',
			title: 'Gambar QRIS',
			type: 'image',
			group: 'kontak',
		}),
		defineField({
			name: 'mapsUrl',
			title: 'Google Maps URL',
			type: 'url',
			group: 'kontak',
		}),
		defineField({
			name: 'linktree',
			title: 'Linktree URL',
			type: 'url',
			group: 'sosmed',
		}),
		defineField({
			name: 'socialMedia',
			title: 'Sosial Media',
			type: 'object',
			group: 'sosmed',
			fields: [
				{ name: 'facebook', title: 'Facebook', type: 'url' },
				{ name: 'instagram', title: 'Instagram', type: 'url' },
				{ name: 'youtube', title: 'YouTube', type: 'url' },
				{ name: 'tiktok', title: 'TikTok', type: 'url' },
			],
		}),
		defineField({
			name: 'tagline',
			title: 'Tagline Beranda',
			type: 'string',
			group: 'beranda',
		}),
		defineField({
			name: 'heroTitle',
			title: 'Judul Hero',
			type: 'string',
			group: 'beranda',
		}),
		defineField({
			name: 'heroDescription',
			title: 'Deskripsi Hero',
			type: 'text',
			rows: 3,
			group: 'beranda',
		}),
		defineField({
			name: 'heroCtaText',
			title: 'Teks Tombol CTA',
			type: 'string',
			initialValue: 'Donasi Sekarang',
			group: 'beranda',
		}),
		defineField({
			name: 'heroCtaLink',
			title: 'Link Tombol CTA',
			type: 'string',
			initialValue: '/donasi',
			group: 'beranda',
		}),
		defineField({
			name: 'stats',
			title: 'Statistik Beranda',
			type: 'array',
			of: [
				{
					type: 'object',
					fields: [
						{ name: 'number', title: 'Angka/Nilai', type: 'string' },
						{ name: 'label', title: 'Label', type: 'string' },
					],
					preview: {
						select: {
							title: 'number',
							subtitle: 'label',
						},
					},
				},
			],
			group: 'beranda',
		}),
		defineField({
			name: 'breadcrumbLabels',
			title: 'Label Breadcrumb',
			type: 'object',
			group: 'tampilan',
			fields: [
				{ name: 'beranda', title: 'Beranda', type: 'string' },
				{ name: 'tentang', title: 'Tentang', type: 'string' },
				{ name: 'program', title: 'Program', type: 'string' },
				{ name: 'kegiatan', title: 'Kegiatan', type: 'string' },
				{ name: 'donasi', title: 'Donasi', type: 'string' },
				{ name: 'kontak', title: 'Kontak', type: 'string' },
				{ name: 'blog', title: 'Blog', type: 'string' },
				{ name: 'galeri', title: 'Galeri', type: 'string' },
				{ name: 'faq', title: 'FAQ', type: 'string' },
			],
		}),
		defineField({
			name: 'emptyStateTexts',
			title: 'Teks Saat Kosong',
			type: 'object',
			group: 'tampilan',
			fields: [
				{ name: 'gallery', title: 'Galeri', type: 'string' },
				{ name: 'kegiatan', title: 'Kegiatan', type: 'string' },
				{ name: 'blog', title: 'Blog', type: 'string' },
			],
		}),
		defineField({
			name: 'kategoriLabels',
			title: 'Label Kategori (pendidikan/keagamaan/sosial/umum)',
			type: 'object',
			group: 'tampilan',
			fields: [
				{ name: 'pendidikan', title: 'Pendidikan', type: 'string' },
				{ name: 'keagamaan', title: 'Keagamaan', type: 'string' },
				{ name: 'sosial', title: 'Sosial Kemanusiaan', type: 'string' },
				{ name: 'umum', title: 'Umum', type: 'string' },
			],
		}),
		defineField({
			name: 'navItems',
			title: 'Menu Navigasi',
			type: 'array',
			group: 'tampilan',
			of: [
				{
					type: 'object',
					fields: [
						{ name: 'label', title: 'Label', type: 'string' },
						{ name: 'href', title: 'Tautan', type: 'string' },
					],
					preview: {
						select: { title: 'label', subtitle: 'href' },
					},
				},
			],
			initialValue: [
				{ label: 'Beranda', href: '/' },
				{ label: 'Tentang', href: '/tentang' },
				{ label: 'Program', href: '/program' },
				{ label: 'Kegiatan', href: '/kegiatan' },
				{ label: 'Kontak', href: '/kontak' },
			],
		}),
		defineField({
			name: 'ctaButton',
			title: 'Tombol CTA (Navbar)',
			type: 'object',
			group: 'tampilan',
			fields: [
				{
					name: 'text',
					title: 'Teks Tombol',
					type: 'string',
					initialValue: 'Donasi',
				},
				{
					name: 'href',
					title: 'Tautan',
					type: 'string',
					initialValue: '/donasi',
				},
				{
					name: 'isEnabled',
					title: 'Aktif',
					type: 'boolean',
					initialValue: true,
				},
			],
		}),
		defineField({
			name: 'galleryCategoryGradients',
			title: 'Gradients Kategori Galeri',
			type: 'array',
			of: [
				{
					type: 'object',
					fields: [
						{ name: 'category', title: 'Kategori', type: 'string' },
						{ name: 'gradient', title: 'Gradient CSS', type: 'string' },
					],
					preview: {
						select: {
							title: 'category',
							subtitle: 'gradient',
						},
					},
				},
			],
			group: 'tampilan',
		}),
		defineField({
			name: 'galleryCategoryIcons',
			title: 'Ikon Kategori Galeri',
			type: 'array',
			of: [
				{
					type: 'object',
					fields: [
						{ name: 'category', title: 'Kategori', type: 'string' },
						{ name: 'icon', title: 'Nama Ikon', type: 'string' },
					],
					preview: {
						select: {
							title: 'category',
							subtitle: 'icon',
						},
					},
				},
			],
			group: 'tampilan',
		}),
		defineField({
			name: 'notFoundTitle',
			title: 'Judul Halaman 404',
			type: 'string',
			initialValue: 'Halaman Tidak Ditemukan',
			group: 'umum',
		}),
		defineField({
			name: 'notFoundDescription',
			title: 'Deskripsi Halaman 404',
			type: 'text',
			rows: 2,
			initialValue: 'Maaf, halaman yang Anda cari tidak tersedia atau telah dipindahkan.',
			group: 'umum',
		}),
	],
	preview: {
		select: {
			title: 'siteName',
		},
	},
})
