/**
 * IconName — Type definition for icon names
 *
 * Centralized type for all available icon names.
 * Exported for use in components that accept icon props.
 */
export type IconName =
	| 'heart'
	| 'arrow-right'
	| 'arrow-left'
	| 'arrow-up'
	| 'arrow-down'
	| 'book'
	| 'home'
	| 'location'
	| 'phone'
	| 'email'
	| 'globe'
	| 'whatsapp'
	| 'external-link'
	| 'star'
	| 'check-circle'
	| 'credit-card'
	| 'qrcode'
	| 'facebook'
	| 'instagram'
	| 'tiktok'
	| 'youtube'
	| 'twitter'
	| 'linkedin'
	| 'copy'
	| 'check'
	| 'camera'
	| 'calendar'
	| 'image'
	| 'menu'
	| 'clock'
	| 'chevron-right'
	| 'chevron-left'
	| 'chevron-down'
	| 'close'
	| 'download'
	| 'share'
	| 'search'
	| 'filter'
	| 'bank'
	| 'wallet'
	| 'play'
	| 'pause'
	| 'error'
	| 'warning'
	| 'info'
